FROM python:3.11-slim

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir --disable-pip-version-check -r requirements.txt

COPY . .

RUN chmod 0555 /usr/src/app/kubernetes-entrypoint.sh

# @@

ENTRYPOINT ["python", "./s3gc.py"]
# CMD ["--help" ]
